apiVersion: v1
kind: ConfigMap
metadata:
  name: beatbox-api-config
  labels:
    app: beatbox-api
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/music_db"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  MANAGEMENT_OTLP_TRACING_ENDPOINT: "http://tempo:4318/v1/traces"
  LOGGING_LOKI_URL: "http://loki:3100/loki/api/v1/push"
  SERVER_PORT: "8080"
