apiVersion: v1
kind: Secret
metadata:
  name: beatbox-api-secret
  labels:
    app: beatbox-api
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "CHANGE_ME"
